#!/bin/bash

[ "$1" == "--help" ] && {
	cat <<- FIN >&2
	kkcw: kkc wrapper
	usage: echo <words> | kkcw

	copyright 2019 Ryuichi Ueda
	Licensed under the GNU GPLv3. See the file COPYING for details.
	FIN
	exit 1
}

single () {
	kkc <<< "$1 1"                  |
	grep -o '0: .*'                 |
	sed 's@<\([^/]*\)/[^>]*>@\1@g'  |
	sed 's/^0: //'
}

multi () {
	xargs -n 1                           | 
	while read w ; do single "$w"; done  |
	xargs
}

multi
